function [metadata, missing] = get_metadata(names, description)
% GET_METADATA extracts the metadata for the variables of interest
% from the original varsHTML description.
%
% USAGE: [metadata, missing] = get_metadata(names, description)
% where metadata is a cell array with the information, names are
% the variable names we wish to retrieve and description is the
% description according to the varsHTML variable.
%
% EXAMPLE: [metadata, missing] = get_metadata(names, varsHTML)
%
% See also: steveOriginalReadme.
    
% preallocate metadata
metadata = cell(size(names));
n_desc = size(description, 1);

% $$$ additional_desc = {...
% $$$     '22599-',...
% $$$     '22605-',...
% $$$     '22620-',...
% $$$     '30000-',...
% $$$     '30010-',...
% $$$     '30020-',...
% $$$     '30030-',...
% $$$     '30040-',...
% $$$     '30050-',...
% $$$     '30060-',...
% $$$     '30070-',...
% $$$     '30080-',...
% $$$     '30090-',...
% $$$     '30100-',...
% $$$     '30110-',...
% $$$     '30120-',...
% $$$     '30130-',...
% $$$     '30140-',...
% $$$     '30150-',...
% $$$     '30160-',...
% $$$     '30180-',...
% $$$     '30190-',...
% $$$     '30200-',...
% $$$     '30210-',...
% $$$     '30220-',...
% $$$     '30230-',...
% $$$     '30240-',...
% $$$     '30250-',...
% $$$     '30260-',...
% $$$     '30270-',...
% $$$     '30280-',...
% $$$     '30290-',...
% $$$     '30300-'};

% preprocess descriptions
for desc_entry = 3:n_desc
    code = strsplit(description{desc_entry, 2}, '-');
    description{desc_entry, 2} = strcat(code{1}, '-');
    
    % Account for cases where there are multiple visits
    if isempty(description{desc_entry, 4})
        description{desc_entry, 4} = description{desc_entry - 1, 4};
    end
    
end

% generate metadata for the variables considered
missing = [];
for name_entry = 1:size(names, 1)
    
    % Search for a description match
    desc_entry = 1;
    while ~strcmp(description{desc_entry, 2}, names{name_entry}) && ...
            desc_entry < n_desc
        desc_entry = desc_entry + 1;
    end
        
    if desc_entry >= n_desc
        fprintf('!!! Warning - Variable not found !\n');
        missing = [missing, name_entry];
    else    
        metadata{name_entry} = description{desc_entry, 4};
    end
end

end